### ISSUE TITLE
[CRITICAL] Correct use of state

### ISSUE THREAD

**Issue by ale1313** [fedegomezdev/DrinkApp#2]
Podrias explicarme en este issue el por que de elegir esta manera de trabajar con el state? Es totalmente diferente al estandar con el cual trabajamos (no quiero decir que este mal, simplemente no veo la eficacia). Por favor, revisa el boilerplate para ver cual es la manera en la cual manipulamos el state correctamente.

https://github.com/fedegomezdev/DrinkApp/blob/1e9889a698a33ce61c09bbddb55654426a12a447/src/screens/Drinks/DrinkScreenE.tsx#L20

**Comment by fedegomezdev** [comment]
Hable con javi y me dijo que daba igual si usaba hooks o la forma tradicional
