### ISSUE TITLE
[MINOR] Use colors from Pallete

### ISSUE THREAD

**Issue by LcsGrz** [fedegomezdev/DrinkApp#21]
Agrega el color a la paleta & usalo desde ahi
https://github.com/fedegomezdev/DrinkApp/blob/530fc13c36e8d1a921ba2aa22d3ab8d3349de760/src/screens/Drinks/style.ts#L10

**Comment by fedegomezdev** [comment]
Este ni lo estaba usando , no sé por qué quedo ahi jajaja, ya lo saqué.
