### ISSUE TITLE
[Minor] What is this naming?

### ISSUE THREAD

**Issue by ale1313** [fedegomezdev/DrinkApp#3]
Esto no es nada grave, solo quiero saber el por que elegiste agregar una E al final del nombre de la funcion y del archivo. Recuerda que es imperativo que sigas las normas de nombramiento de archivos y declaraciones, que sean claras y entendibles.

https://github.com/fedegomezdev/DrinkApp/blob/1e9889a698a33ce61c09bbddb55654426a12a447/src/screens/Drinks/DrinkScreenE.tsx#L18

**Comment by fedegomezdev** [comment]
Debe haber sido un error de tipeo, no recuerdo, pero ya esta resuelto tambien
