### ISSUE TITLE
[Question] Unnecesary function?

### ISSUE THREAD

**Issue by ale1313** [fedegomezdev/DrinkApp#5]
Que funcion cumple este metodo? No es algo convencional que deberias estar obligado a utilizar en este flow.

https://github.com/fedegomezdev/DrinkApp/blob/1e9889a698a33ce61c09bbddb55654426a12a447/src/screens/Drinks/DrinkScreenE.tsx#L36

**Comment by fedegomezdev** [comment]
La utilizo para despachar la accion tieniendo en cuenta los cambios del state , mas especificamente del input
